# Generated by Django 3.2 on 2022-11-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20221129_1951'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='label',
            field=models.ForeignKey(blank=True, default='1', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='products.label'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='products.record'),
        ),
    ]
