# Generated by Django 3.2 on 2022-11-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221130_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='review',
            name='label',
        ),
    ]
