# Generated by Django 3.2 on 2022-12-02 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20221129_1951'),
        ('reviews', '0005_review_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='label',
            field=models.ForeignKey(default=0, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='products.label'),
        ),
    ]
