# Generated by Django 3.2 on 2022-12-04 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20221203_1855'),
        ('reviews', '0005_alter_review_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='label',
            field=models.ForeignKey(default='1', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='products.label'),
        ),
    ]
