# Generated by Django 3.2 on 2022-10-05 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221005_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.label'),
        ),
    ]
