# Generated by Django 3.2 on 2022-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_record_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='track_list',
        ),
        migrations.AddField(
            model_name='record',
            name='track_list_1',
            field=models.TextField(default='Track'),
        ),
        migrations.AddField(
            model_name='record',
            name='track_list_2',
            field=models.TextField(default='Track'),
        ),
        migrations.AddField(
            model_name='record',
            name='track_list_3',
            field=models.TextField(default='Track'),
        ),
        migrations.AddField(
            model_name='record',
            name='track_list_4',
            field=models.TextField(default='Track'),
        ),
        migrations.AddField(
            model_name='record',
            name='track_list_5',
            field=models.TextField(default='Track'),
        ),
        migrations.AddField(
            model_name='record',
            name='track_list_6',
            field=models.TextField(default='Track'),
        ),
    ]
