# Generated by Django 3.2 on 2022-10-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20221007_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='label',
            new_name='name',
        ),
    ]
