# Generated by Django 3.2 on 2022-10-09 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_label_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='friendly_name',
            field=models.CharField(default='Label', max_length=150),
        ),
        migrations.AlterField(
            model_name='record',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.label'),
            preserve_default=False,
        ),
    ]
