# Generated by Django 3.2 on 2022-10-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20221009_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='friendly_name',
            field=models.CharField(default='1', max_length=150),
        ),
        migrations.AlterField(
            model_name='record',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.label'),
        ),
    ]
