# Generated by Django 3.2 on 2022-11-27 17:29

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20221009_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name_plural': 'Labels'},
        ),
        migrations.RenameField(
            model_name='label',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='label',
            name='friendly_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='record',
            name='label',
            field=models.ForeignKey(default=False, on_delete=products.models.Label, to='products.label'),
        ),
    ]
