# Generated by Django 3.2 on 2022-11-29 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221127_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='track_list_1',
            new_name='track_list',
        ),
        migrations.RemoveField(
            model_name='record',
            name='track_list_2',
        ),
        migrations.RemoveField(
            model_name='record',
            name='track_list_3',
        ),
        migrations.RemoveField(
            model_name='record',
            name='track_list_4',
        ),
        migrations.RemoveField(
            model_name='record',
            name='track_list_5',
        ),
        migrations.RemoveField(
            model_name='record',
            name='track_list_6',
        ),
        migrations.AlterField(
            model_name='record',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.label'),
        ),
        migrations.AlterField(
            model_name='record',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
