# Generated by Django 3.2 on 2022-12-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20221203_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='keywords',
        ),
        migrations.AddField(
            model_name='record',
            name='track',
            field=models.CharField(default='', max_length=100),
        ),
    ]
