# Generated by Django 3.2 on 2022-12-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20221203_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='producer',
            field=models.CharField(default='', max_length=254),
        ),
    ]
