# Generated by Django 3.2 on 2022-12-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_record_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='track',
            field=models.CharField(default='', max_length=500),
        ),
    ]
